### ISSUE TITLE
Nothing to install if there's no `.prototools` file

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/setup-toolchain#11]
If there's no `.prototools` file but there's something in the .moon/toolchain.yml like:

```yaml
bun:
  version: latest
```

the action fails saying that there's nothing to install.

**Comment by milesj** [comment]
@rhuanbarreto Are you referring to the `auto-install` setting? Then this is working as intended, as that's only for proto. For moon, just run some moon commands and it'll install it on demand.

**Comment by rhuanbarreto** [comment]
Thanks for clarifying. As I got the deprecation notice, it would be good to update the CI docs page to point to the right action
