### ISSUE TITLE
bun is not installed if you also have node defined in toolchain

### ISSUE THREAD

**Issue by marcus-sa** [moonrepo/setup-toolchain#15]
![Screenshot from 2024-10-16 13-52-14](https://github.com/user-attachments/assets/2d341691-ecf2-4d9f-a69f-4ebd39f82157)
![Screenshot from 2024-10-16 13-52-03](https://github.com/user-attachments/assets/375984be-91ac-4f6c-8e4f-6ee580ac530e)

**Comment by marcus-sa** [comment]
Bun doesn't appear to be installed at all...

**Comment by milesj** [comment]
@marcus-sa The auto-install is only from `.prototools`, not moon's toolchain.

**Comment by marcus-sa** [comment]
@milesj that's not documented anywhere so that's not what I expected

**Comment by milesj** [comment]
I'll update the docs, but yeah this is how it works. moon's toolchain is just proto internally, so everything is powered by proto, and proto does not read moon config files. You'd have to run moon commands for moon to initiate the install of these tools.
