### ISSUE TITLE
Post action step takes way too long

### ISSUE THREAD

**Issue by theomessin** [moonrepo/setup-toolchain#7]
I've had the post action step consistently take > 1 minute.
Maybe we should have an option to disable cache pruning (or whatever is taking this long).
![image](https://github.com/moonrepo/setup-toolchain/assets/7229472/d3307896-7a6a-450b-b050-500d80379ee3)

**Comment by milesj** [comment]
Ok this is weird, it's a cache hit so it should exit immediately: https://github.com/moonrepo/setup-toolchain/blob/master/post.ts#L34

I'm not entirely sure why it takes that long...

Only thing I can think of is that the glob is slow? https://github.com/moonrepo/setup-toolchain/blob/master/helpers.ts#L47

**Comment by milesj** [comment]
I pushed a small patch, let's see if that helps.

**Comment by iyefrat** [comment]
I also had this issue, this fixed it for me

**Comment by milesj** [comment]
Gonna close this. Not much else I can do here.

There's also the `cache-base` option which can also help.
